table website_sessions
	lineageTag: 8ca30b78-e592-46b1-b383-949041f06cc4

	measure session_quality_score_avg_scaled =
			INT(AVERAGEX(
			    website_sessions,
			    website_sessions[session_quality_score] * 100
			))
		lineageTag: 2afe0dc9-de31-4ef0-94f0-5e405dedcab9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure max_quality_score = 100
		formatString: 0
		lineageTag: 494b10a2-4aaa-42cb-9f0f-16914200f964

	measure target_quality_score = 50
		formatString: 0
		lineageTag: e0b0cabb-aa9a-4e0e-ad1e-c722c74414a1

	column session_id
		dataType: string
		lineageTag: 73f7bf3d-3555-48ab-93df-ef16a9c8bd39
		summarizeBy: none
		sourceColumn: session_id

		annotation SummarizationSetBy = Automatic

	column session_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: cdf9e804-11c8-466a-a990-0a28c7ed299c
		summarizeBy: none
		sourceColumn: session_date

		variation Variation
			isDefault
			relationship: 1ec3957c-df37-44fc-b9fa-2507ccb0ab07
			defaultHierarchy: LocalDateTable_f3bdb72f-fa9c-417c-89d2-60d797cce775.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column customer_id
		dataType: int64
		formatString: 0
		lineageTag: 0f0194ee-abec-494a-90d7-e197fec8f004
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column store_id
		dataType: int64
		formatString: 0
		lineageTag: b4524543-c9d1-47f0-b634-ec866f0ffaf6
		summarizeBy: none
		sourceColumn: store_id

		annotation SummarizationSetBy = Automatic

	column device_type
		dataType: string
		lineageTag: f01bda0e-3dc8-42fb-8846-92c717f820eb
		summarizeBy: none
		sourceColumn: device_type

		annotation SummarizationSetBy = Automatic

	column session_purchase_made
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d9d1f805-c211-4a01-aacd-c46690432002
		summarizeBy: none
		sourceColumn: session_purchase_made

		annotation SummarizationSetBy = Automatic

	column session_duration_minutes
		dataType: int64
		formatString: 0
		lineageTag: cbbb2566-9f6c-42dd-8c21-bba14f3d9c6e
		summarizeBy: sum
		sourceColumn: session_duration_minutes

		annotation SummarizationSetBy = Automatic

	column session_pages_visited
		dataType: int64
		formatString: 0
		lineageTag: 957c6792-616d-42ff-b7ef-99048f195bcc
		summarizeBy: sum
		sourceColumn: session_pages_visited

		annotation SummarizationSetBy = Automatic

	column session_quality_score
		dataType: double
		lineageTag: d915285c-dec0-4dc3-8d89-2ece3f5fad3e
		summarizeBy: sum
		sourceColumn: session_quality_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column browser
		dataType: string
		lineageTag: 76966292-41fd-4def-b804-56d703144786
		summarizeBy: none
		sourceColumn: browser

		annotation SummarizationSetBy = Automatic

	column os
		dataType: string
		lineageTag: 48bda70a-c3cc-4a1b-98ee-92292660a69d
		summarizeBy: none
		sourceColumn: os

		annotation SummarizationSetBy = Automatic

	column os_on_device
		dataType: string
		lineageTag: 158b24f1-6fe7-4306-8dd0-6a4253a59c28
		summarizeBy: none
		sourceColumn: os_on_device

		annotation SummarizationSetBy = Automatic

	partition website_sessions = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\confidenthampter\codebase\bootDev\dataviz-projec\website_sessions.csv"),[Delimiter=",", Columns=10, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"session_id", type text}, {"session_date", type date}, {"customer_id", Int64.Type}, {"store_id", Int64.Type}, {"device_type", type text}, {"browser_os", type text}, {"session_purchase_made", type logical}, {"session_duration_minutes", Int64.Type}, {"session_pages_visited", Int64.Type}, {"session_quality_score", type number}}),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Changed Type", "browser_os", Splitter.SplitTextByDelimiter("|", QuoteStyle.Csv), {"browser_os.1", "browser_os.2"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"browser_os.1", type text}, {"browser_os.2", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"browser_os.1", "browser"}, {"browser_os.2", "os"}}),
				    #"Inserted Merged Column" = Table.AddColumn(#"Renamed Columns", "os_on_device", each Text.Combine({[os], [device_type]}, " on "), type text),
				    #"Replaced Value" = Table.ReplaceValue(#"Inserted Merged Column",null,0.5,Replacer.ReplaceValue,{"session_quality_score"})
				in
				    #"Replaced Value"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

